from __future__ import annotations

from ai_trader.scoring.activity import (
    DEFAULT_ACTIVITY_FLOOR,
    MAX_ZERO_WINDOW_PCT,
    MIN_MEDIAN_TRADES_PER_WINDOW,
    ActivityFloor,
    ActivityStats,
    eligibility_dict,
    measure_activity,
)
from ai_trader.scoring.aggregate import DEFAULT_CVAR_ALPHA, RewardStats, aggregate_reward
from ai_trader.scoring.baselines import (
    Baseline,
    BaselineGate,
    compute_baselines,
    gate,
)
from ai_trader.scoring.cem import CEMConfig, CEMResult, maximize
from ai_trader.scoring.multiwindow import (
    SCHEME_CPCV,
    SCHEME_SINGLE,
    SCHEME_WALK_FORWARD,
    FoldScore,
    MultiWindowValidation,
    resolve_purge_days,
    validate_multiwindow,
)
from ai_trader.scoring.overfit import (
    DeflatedSharpe,
    PBOResult,
    deflated_sharpe_ratio,
    probability_of_backtest_overfitting,
)
from ai_trader.scoring.sample_eval import (
    SampleEvaluation,
    evaluate_baselines,
    evaluate_sample,
    evaluate_sample_detailed,
)
from ai_trader.scoring.scenario_split import ScenarioSplit, split_scenarios
from ai_trader.scoring.search_space import SPACES, ParamSpace, get_space
from ai_trader.scoring.weight_calibration import (
    CALIBRATION_REPORT,
    CalibrationMatrix,
    CalibrationSample,
    TurnoverCostAudit,
    WeightGridPoint,
    WindowComponents,
    candidate_specs,
    evaluate_calibration_sample,
    evaluate_weight_point,
    grid_point,
    load_calibration_report,
    spearman,
    sweep_weights,
    turnover_cost_audit,
)

__all__ = [
    "DEFAULT_ACTIVITY_FLOOR",
    "MAX_ZERO_WINDOW_PCT",
    "MIN_MEDIAN_TRADES_PER_WINDOW",
    "ActivityFloor",
    "ActivityStats",
    "eligibility_dict",
    "measure_activity",
    "DEFAULT_CVAR_ALPHA",
    "RewardStats",
    "aggregate_reward",
    "Baseline",
    "BaselineGate",
    "compute_baselines",
    "gate",
    "CEMConfig",
    "CEMResult",
    "maximize",
    "SCHEME_CPCV",
    "SCHEME_SINGLE",
    "SCHEME_WALK_FORWARD",
    "FoldScore",
    "MultiWindowValidation",
    "resolve_purge_days",
    "validate_multiwindow",
    "DeflatedSharpe",
    "PBOResult",
    "deflated_sharpe_ratio",
    "probability_of_backtest_overfitting",
    "ScenarioSplit",
    "split_scenarios",
    "SPACES",
    "ParamSpace",
    "get_space",
    "SampleEvaluation",
    "evaluate_baselines",
    "evaluate_sample",
    "evaluate_sample_detailed",
    "CALIBRATION_REPORT",
    "CalibrationMatrix",
    "CalibrationSample",
    "TurnoverCostAudit",
    "WeightGridPoint",
    "WindowComponents",
    "candidate_specs",
    "evaluate_calibration_sample",
    "evaluate_weight_point",
    "grid_point",
    "load_calibration_report",
    "spearman",
    "sweep_weights",
    "turnover_cost_audit",
]
